import { Container, Typography } from "@mui/material";

import React from "react";
const AboutPage = () => {
  return (
    <Container maxWidth="md">
      <Typography variant="h1">About Us</Typography>
      <Typography className="aboutText">
        Welcome to the Worker Management System project! i'm excited to share
        more about the project .
        <br />
        <br />
      </Typography>
      <Typography variant="h4" color="primary">
        Project Overview
      </Typography>
      <Typography className="aboutText">
        The Worker Management System is a full-stack application designed to
        streamline worker management tasks. With a Node.js server and a React
        frontend, the system handles three MongoDB databases for workers, tasks,
        and customers. It provides CRUD operations for workers and a
        comprehensive management interface for administrators
        <br />
        <br />
      </Typography>
      <Typography variant="h4" color="primary">
        How It Works
      </Typography>
      <Typography className="aboutText">
        Our platform is easy to use and requires no technical expertise.
        <br />
        We have two types of workers, an admin and a worker. Every worker
        handles his own tasks, and admins can see and manage the tasks of all
        workers.
        <br /> <br />
      </Typography>
      <Typography variant="h4" color="primary">
        Our Goals
      </Typography>
      <Typography className="aboutText">
        <li>
          • <strong>Efficiency:</strong> Simplify worker management tasks and
          improve overall efficiency in task allocation and completion.
        </li>
        <li>
          • <strong>Transparency:</strong> Provide transparency in task status
          and worker performance, empowering administrators to make informed
          decisions.
        </li>
        <li>
          • <strong>Scalability:</strong> Design the system to be scalable,
          accommodating the growth of worker teams and task complexity.
        </li>

        <br />
        <br />
      </Typography>

      <Typography variant="h4" color="primary">
        Contact Me
      </Typography>
      <Typography className="aboutText">
        I appreciate your interest in the Worker Management System project. If
        you have questions, suggestions, or would like to contribute, feel free
        to contact me
        <li>
          <strong>Email:</strong>{" "}
          <a href="mailto:estybkatz@gmail.com">estybkatz@gmail.com</a>
        </li>
        <li>
          <strong>GitHub:</strong>{" "}
          <a
            href="https://github.com/estybkatz"
            target="_blank"
            rel="noopener noreferrer"
          >
            GitHub Profile
          </a>
        </li>
        We value your input and are always looking for ways to improve our
        platform and better serve our users. <br />
        <br />
        <br />
        <br />
        <br />
      </Typography>
      <Typography variant="h2" color="primary">
        Site Structure
      </Typography>
      <Typography>
        <br />
      </Typography>

      <Typography variant="h4" color="primary">
        Users{" "}
      </Typography>
      <Typography className="aboutText">
        Every System has a first admin, (generated by us)<br></br>
        The admin can register new workers, and manage the tasks of all workers.
        <br />
        The regular users can add tasks, view their own tasks, and set them as
        done.
      </Typography>

      <Typography variant="h4" color="primary">
        The Navbar
      </Typography>
      <Typography className="aboutText">
        The site contains an upper navbar, which changes according to whether
        the user is logged in or not, allowing navigation to the pages allowed
        for the user.
        <br />
        The Navbar contains a search function, which will search in the current
        page.
        <br />
        If the user is logged in, the navbar contains an avatar that allows the
        user to edit his profile or logout.
        <br /> The Navbar contains a sun/moon icon to change the theme of the
        site from dark to light. <br />
        <br />
      </Typography>

      <Typography variant="h4" color="primary">
        The Card Pages
      </Typography>
      <Typography className="aboutText">
        Every customer has his own card.
        <br />
        The site has 2 different ways to view cards.
        <br /> All the cards in the homepage.
        <br />
        The Fav Cards page, in which you can view your favorite cards.
        <br />
      </Typography>
      <Typography variant="h4" color="primary">
        The Footer
      </Typography>
      <Typography className="aboutText">
        The site contains a footer which links to the about page, and favorites
        page and my cards. <br /> <br />
      </Typography>
      <Typography variant="h4" color="primary">
        User types and options
      </Typography>
      <Typography className="aboutText">
        Available options for users: This site has 2 types of users, a regular
        user, and an admin user.
        <br />
        All registered users can favorite cards and view only the cards they
        favorited. A favorited card has the heart-shaped favorite button colored
        red, while an unfavorited card has it colored blue. <br /> A user can
        view their favorite cards using the Fav Cards page.
        <br />
        An admin user can register new users and has a management interface of
        all the users, tasks, and customers.
        <br />
        After creating a card, an admin user can edit or delete the cards they
        made.
        <br />
        To register, contact the admin by email.
        <br /> Any user can edit their profile pages. <br /> <br />
      </Typography>
    </Container>
  );
};

export default AboutPage;
